### ISSUE TITLE
Error in version 2.0.0

### ISSUE THREAD

**Issue by gifary** [xendit/xendit-sdk-android#28]
I am getting this error when initializing Xendit

`java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/converter/scalars/ScalarsConverterFactory;
        at com.xendit.Logger.Logger.<init>(Logger.java:68)
        at com.xendit.Xendit.<init>(Xendit.java:83)
        at com.app.cozyresidence.fragments.Checkout.createSingleUseToken(Checkout.java:859)
        at com.app.cozyresidence.fragments.Checkout.access$100(Checkout.java:120)
        at com.app.cozyresidence.fragments.Checkout$2.onClick(Checkout.java:433)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit2.converter.scalars.ScalarsConverterFactory" on path: DexPathList[[zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/base.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_resources_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.xendit.Logger.Logger.<init>(Logger.java:68) 
        at com.xendit.Xendit.<init>(Xendit.java:83) 
        at com.app.cozyresidence.fragments.Checkout.createSingleUseToken(Checkout.java:859) 
        at com.app.cozyresidence.fragments.Checkout.access$100(Checkout.java:120) 
        at com.app.cozyresidence.fragments.Checkout$2.onClick(Checkout.java:433) 
        at android.view.View.performClick(View.java:6266) 
        at android.view.View$PerformClick.run(View.java:24730) 
        at android.os.Handler.handleCallback(Handler.java:793) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:173) 
        at android.app.ActivityThread.main(ActivityThread.java:6698) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.app.cozyresidence-E__WvWfp1dQ4pjmBRRI5TQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:681)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:714)
        at android.app.LoadedApk.getResources(LoadedApk.java:941)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2254)
2019-03-26 11:21:35.291 21797-21797/com.app.cozyresidence E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5755)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
        at android.os.Handler.dispatchMessage(Handler.java:105)`

Any suggenstion for me, how to fix this issue?

**Comment by gifary** [comment]
I fixed by adding those libraries
implementation 'io.sentry:sentry-android:1.7.10'
    implementation 'com.android.volley:volley:1.1.1'
    implementation 'com.squareup.retrofit2:converter-scalars:2.5.0'

but now I am getting another error

` java.lang.NoSuchFieldError: No static field webView_XenditActivity of type I in class Lcom/xendit/R$id; or its superclasses (declaration of 'com.xendit.R$id' appears in /data/app/com.app.cozyresidence-FRWw05ykjbQjgawg5e7n5Q==/split_lib_slice_9_apk.apk)
        at com.xendit.XenditActivity.onCreate(XenditActivity.java:45)
        at android.app.Activity.performCreate(Activity.java:7040)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)`

**Comment by Gurupreet** [comment]
Same here why we need to add those another lib seriously. 
Version 1.1.0 works fine without those but it crash at auth process.
